import js from '@eslint/js';
import { configs, plugins } from 'eslint-config-airbnb-extended';

export default [
    {
        ignores: ['.next/**', 'out/**', 'build/**', 'node_modules/**', 'prisma/generated/**', 'next-env.d.ts'],
    },
    {
        name: 'js/config',
        ...js.configs.recommended,
    },
    plugins.stylistic,
    plugins.importX,
    ...configs.base.recommended,
    plugins.react,
    plugins.reactHooks,
    plugins.reactA11y,
    plugins.next,
    ...configs.next.recommended,
    plugins.typescriptEslint,
    ...configs.base.typescript,
    ...configs.next.typescript,
    {
        rules: {
            'import/no-default-export': 'off',
            'react/function-component-definition': 'off',
            'jsx-a11y/control-has-associated-label': 'off',
            '@next/next/no-img-element': 'off',

            '@stylistic/indent': ['error', 4, { SwitchCase: 1 }],
            '@stylistic/jsx-indent-props': 'off',
            'react/jsx-indent': 'off',
            'react/jsx-indent-props': 'off',
            '@typescript-eslint/no-shadow': 'off',
            '@stylistic/arrow-parens': ['error', 'always'],
            '@stylistic/brace-style': ['error', '1tbs', { allowSingleLine: false }],
            '@stylistic/quote-props': ['error', 'consistent-as-needed'],
            '@stylistic/object-curly-newline': ['error', { multiline: true, consistent: true }],
            '@stylistic/object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
            '@stylistic/max-len': ['error', { code: 192 }],
            '@stylistic/linebreak-style': 'off',
            '@stylistic/jsx-one-expression-per-line': 'off',
            '@stylistic/member-delimiter-style': ['error', { multiline: { delimiter: 'semi', requireLast: true }, singleline: { delimiter: 'comma' } }],

            'class-methods-use-this': 'off',
            'curly': ['error', 'multi-line'],
            'object-shorthand': ['error'],
            'strict': ['error', 'global'],
            'no-restricted-syntax': 'off',
            'no-case-declarations': 'off',
            'no-bitwise': 'off',
            'no-plusplus': 'off',
            'no-shadow': 'off',
            'no-continue': 'off',
            'radix': 'off',
            'no-use-before-define': 'off',
            'no-param-reassign': 'off',
            'no-undef-init': 'off',
            'no-undef': 'off',
            'no-nested-ternary': 'off',
            'no-underscore-dangle': 'off',
            'default-case': 'off',

            'react/jsx-filename-extension': ['error', { extensions: ['.jsx', '.tsx'] }],
            'react/no-unused-state': 'off',
            'react/prop-types': 'off',
            'react/require-default-props': 'off',
            'react/no-unused-prop-types': 'off',
            'react/destructuring-assignment': 'off',
            'react/jsx-props-no-spreading': 'off',
            'react/no-unescaped-entities': 'off',
            'react/jsx-uses-react': 'off',
            'react/react-in-jsx-scope': 'off',

            'react-hooks/rules-of-hooks': 'error',
            'react-hooks/exhaustive-deps': 'warn',
            'react-hooks/refs': 'off',
            'react-hooks/use-memo': 'off',

            'import-x/no-extraneous-dependencies': ['error', {
                devDependencies: [
                    'eslint.config.mjs',
                    'prisma.config.ts',
                    'prisma/seed.ts',
                    'approve-cors.ts',
                ],
            }],
            'import-x/prefer-default-export': 'off',
            'import-x/newline-after-import': 'error',
            'import-x/extensions': 'off',
            'import-x/no-unresolved': 'off',

            '@typescript-eslint/no-unused-vars': ['error', {
                vars: 'all',
                varsIgnorePattern: '^_',
                args: 'after-used',
                argsIgnorePattern: '^_',
            }],
            '@typescript-eslint/consistent-type-definitions': 'error',
            '@typescript-eslint/no-namespace': 'off',
            '@typescript-eslint/naming-convention': 'off',
        },
    },
];
